# Generated by Django 3.2.5 on 2023-06-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=15)),
                ('assunto', models.TextField(max_length=20)),
                ('mensagem', models.TextField(max_length=40)),
            ],
        ),
    ]
